# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_msg', models.CharField(max_length=10000)),
                ('alert_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listener_key', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Listener',
            fields=[
                ('listener_topic', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='key',
            name='listener',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.Listener'),
        ),
        migrations.AddField(
            model_name='alert',
            name='key',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='alerts.Key'),
        ),
        migrations.AlterUniqueTogether(
            name='key',
            unique_together=set([('listener', 'listener_key')]),
        ),
    ]
