# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(max_length=100)),
                ('asset_data', models.FileField(upload_to='assets/')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('feature_uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('feature_data', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('layer_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='piazza_consumer.Asset')),
                ('feature', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='piazza_consumer.Feature')),
            ],
        ),
        migrations.AddField(
            model_name='feature',
            name='layer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='piazza_consumer.Layer'),
        ),
    ]
