# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(max_length=100)),
                ('asset_data', models.FileField(upload_to='assets/')),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listener_key', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='piazza_consumer.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='Listener',
            fields=[
                ('listener_topic', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_body', models.CharField(max_length=10000)),
                ('message_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('key', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='piazza_consumer.Key')),
            ],
        ),
        migrations.AddField(
            model_name='links',
            name='message',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='piazza_consumer.Message'),
        ),
        migrations.AddField(
            model_name='key',
            name='listener',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piazza_consumer.Listener'),
        ),
        migrations.AlterUniqueTogether(
            name='key',
            unique_together=set([('listener', 'listener_key')]),
        ),
    ]
